[[plugins]]
package = "netlify-plugin-flutter"
   [plugins.inputs]
    channel = "stable"
[build]
command = "flutter build web --release"
publish = "build/web"
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"