name: maps_my_rekso
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  intl: 0.18.1
  get_storage: 2.0.3
  permission_handler: ^10.3.0
  shared_preferences: ^2.2.2
  # date time
  time_range: ^1.1.0
  syncfusion_flutter_datepicker: ^22.2.10
  # time_range_picker: ^2.2.0
  dio: ^5.5.0+1
  flutter_animate: ^4.5.0

  # firebase
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  firebase_database: ^10.3.5

  # flutter map leaflet
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  latlng: ^1.0.0
  flutter_map_marker_cluster: any
  flutter_map_location_marker: ^8.0.2
  geolocator: ^10.1.0
  flutter_map_compass: ^1.0.1
  get: 4.6.6
  flutter_map_tappable_polyline: ^6.0.0

  hexcolor: ^3.0.1
  google_fonts: ^5.1.0
  flutter_svg: ^1.0.3
  photo_view: ^0.15.0
  flutter_easyloading: ^3.0.5

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts:
      - family: BerlinSans
        fonts:
          - asset: assets/fonts/BRLNSDB.TTF
            weight: 700
  assets:
    - assets/icons/
    - assets/images/
  uses-material-design: true

